### ISSUE TITLE
Can we have project release notes?

### ISSUE THREAD

**Issue by kedar2a** [dgilland/hashfs#10]
@dgilland , thank you for the fantastic work, we are using hashFS from last 2 years.

Started with hashFS version: [`0.6.0`](https://github.com/gnowledge/gstudio/blob/master/requirements.txt#L24). But now I can see the latest release is `0.7.0`. Can we know what are the changes/updates to-dos from code PoV?

I think release notes is a perfect document to highlight those things. If features and notes come forward then we are excited to upgrade to newer version :+1:

**Comment by dgilland** [comment]
They are in CHANGES.rst: https://github.com/dgilland/hashfs/blob/master/CHANGES.rst
