### ISSUE TITLE
File creation and directory creation should respect the umask

### ISSUE THREAD

**Issue by CMCDragonkai** [dgilland/hashfs#14]
I noticed that even though my shell umask is `027`, it ends up creating files that are readable by other.

I think by default the `fmode` and `dmode` should be reconciled against the process umask.

**Comment by dgilland** [comment]
I'm not sure this would be changed, but it can be overridden fairly easily. That method could be made a part of hashfs but I just don't know if it would be made the default.

**Comment by CMCDragonkai** [comment]
Why do you think it shouldn't be the default? The umask is pretty common Linux (Unix?) concept that is supposed to govern how our programs create new file permissions by default. I don't know how this would work in Windows though.

**Comment by dgilland** [comment]
I don't have a strong opinion either way. Back when I first created this library, the current defaults were what I needed most of the time.
