### ISSUE TITLE
Integrating with Pyfilesystem

### ISSUE THREAD

**Issue by CMCDragonkai** [dgilland/hashfs#15]
It seems that if it's possible to put together hashfs and pyfilesystem, we get the ability to create content addressed filesystem on any filesystem including S3... etc, which can be easier and more portable than relying on FUSE.

The main work would be to abstract the underlying fs calls to go through a proxy object, where by default would just be the OS local filesystem, but then we can pass other kinds of filesystems.

**Comment by sritchie** [comment]
This is a great idea; I'm going to take a crack at this to see how it shakes out.

**Comment by CMCDragonkai** [comment]
Will you need to fork this project?

**Comment by sritchie** [comment]
Yeah, @CMCDragonkai , I'm working on a fork now - we'll see if @dgilland is interested in the final changes once I get it all sorted.

**Comment by sritchie** [comment]
Okay, here it is... https://gist.github.com/sritchie/02d80b6af62305158b97f416188675b0

The change is dramatic enough that I'm guessing @dgilland is not going to be interested, but this is what it looks like to make this happen.

**Comment by CMCDragonkai** [comment]
Do you have a diff?

On 31 January 2020 09:18:07 GMT+13:00, Sam Ritchie <notifications@github.com> wrote:
>Okay, here it is...
>https://gist.github.com/sritchie/02d80b6af62305158b97f416188675b0
>
>The change is dramatic enough that I'm guessing @dgilland is not going
>to be interested, but this is what it looks like to make this happen.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dgilland/hashfs/issues/15#issuecomment-580441062

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sritchie** [comment]
The diff is so extreme that it's not really useful, but here goes: https://github.com/dgilland/hashfs/pull/18

Feel free to use if you like!
