### ISSUE TITLE
Out of memory in Stream object iterator

### ISSUE THREAD

**Issue by vikonnikov** [dgilland/hashfs#17]
Please, pay attention on line:
https://github.com/dgilland/hashfs/blob/4a31a9ceb8aff39de4ea5448c189d6a7df3e55f5/hashfs/hashfs.py#L413

It always loads entire file to memory. We spend a lot of time to understand what happen with large files on our production server.

I suppose that can fix problem:

```python
while True:
    data = self._obj.read(CHUNK_SIZE)
```

**Comment by dgilland** [comment]
Fix released in [v0.7.2](https://pypi.org/project/hashfs/0.7.2/).
