### ISSUE TITLE
fs.count() and fs.size() hangs forever

### ISSUE THREAD

**Issue by sandywater** [dgilland/hashfs#2]
When you get a file system with > 3TBs of files in it the algorithm becomes very inefficient.

It might make more sense to have a running tally stored in a dot-files somewhere in the root of the fs and just reference that.  Thanks.

**Comment by dgilland** [comment]
Under the hood, those methods are using `os.walk`. However, it looks like a faster implementation, `os.scandir`, was made available in Python >= 3.5. It's also available as a standalone module here: https://github.com/benhoyt/scandir.

I wonder if `scandir` would improve things enough to make it usable with a directory of that size.

Would you be able to do a quick check to see how `scandir` performs on your >3TB of files?

Something like the following:

```
# If not on Python 3.5
$ pip install scandir
```

``` python
import os

try:
    from os import scandir, walk
except ImportError:
    from scandir import scandir, walk

def files(root):
    for folder, subfolders, files in walk(root):
        for file in files:
            yield os.path.abspath(os.path.join(folder, file))

def count(root):
    count = 0
    for _ in files(root):
        count += 1
    return count

def size(root):
    total = 0
    for path in files(root):
        total += os.path.getsize(path)
    return total

large_dir = '/path/to/large/dir'
print(count(large_dir))
print(size(large_dir))
```

**Comment by sandywater** [comment]
Thanks for the quick response.

I ran the script and here was the output:

``` bash
$ time python file_test.py
1092662
1106961586081
python file_test.py  81.31s user 87.19s system 9% cpu 29:59.58 total
```

81 seconds !! :scream_cat:

**Comment by dgilland** [comment]
Mind running some more tests?

Can you run the script again but separate the `count()` and `size()` calls to see how long each one takes individually?

Then, how long for something that uses the command line more directly:

``` python
import os

# Count files using "find".
os.system('find /path/to/dir -type f | wc -l')
```

Curious to see how big a difference there is between them.

I'd prefer not to have to introduce some kind of file-system cache that keeps a record of the count/size of a HashFS directory, but I'd be willing to implement something that shells out to the command line if there are significant performance gains.

**Comment by sandywater** [comment]
Count Test:

``` bash
$ time python count_test.py
1166883
python count_test.py  13.61s user 4.46s system 53% cpu 33.798 total
```

Size Test:

``` bash
$ time python size_test.py
1237861972848
python size_test.py  18.13s user 6.37s system 43% cpu 55.920 total
```

Find Test:

``` bash
$ time python other_test.py
1139761
python other_test.py  1.50s user 4.43s system 2% cpu 3:46.66 total
```

Our private cloud is a little 'iffy' so I am going to re-run the first test to get another base line.

``` bash
$ time python file_test.py
1168599
1239127021168
python file_test.py  32.41s user 10.84s system 97% cpu 44.481 total
```

**Comment by dgilland** [comment]
I've implemented usage of the `scandir` package on Python < 3.5. I've decided not to implement something that uses the command line directly (like `find`). However, it's easy enough for someone to subclass `count` or `size` with a faster, more platform specific implementation (e.g. a Linux/Windows only solution).
