### ISSUE TITLE
Suggest using pathlib instead of os.path.

### ISSUE THREAD

**Issue by ramwin** [dgilland/hashfs#20]
The [pahtlib.Path](https://docs.python.org/3.9/library/pathlib.html#correspondence-to-tools-in-the-os-module) module offers high-level path objects.

```
# old usage:
relpath = os.path.join(self.root, file):
if os.path.isfile(relpath):
    return relpath

# new usage
relpath = self.root.joinpath(file)
# relpath = self.root / file  # this also works
if relpath.exists():
    return relpath
```

**Comment by ramwin** [comment]
Hello, @dgilland , I create a pull request to fix this issue.
#21

**Comment by dgilland** [comment]
After some consideration, I'd like to maintain the current implementation in order to not break compatibility.
