### ISSUE TITLE
Create the directory on init.

### ISSUE THREAD

**Issue by ramwin** [dgilland/hashfs#22]
In my scenario, I use hashfs to store a lot of file. E.g. 1000 files in a directory, the depth and width is 2.  
During save files, it always check if the parent folder exists. So I want to create all the 256 directory first and skip the check in the following usage.
Is this imporevement useful. Can I create a pull request to it?

**Comment by ramwin** [comment]
[Here](https://github.com/dgilland/hashfs/pull/19/commits/f524adc3bde43f80c4c001f3d74ee1a1c9576f04) is the snippet.

**Comment by ramwin** [comment]
By the way. A process will be called many times and the HashFS may be inited many times. So I leave the user determining where they should call the method `init_all_sub_directory` or not.

**Comment by dgilland** [comment]
Feel free to subclass `HashFS` in your application to override the default behavior to customize it for your use case.
