### ISSUE TITLE
distutils.dir_util.mkpath won't create the same directory twice

### ISSUE THREAD

**Issue by maparent** [dgilland/hashfs#8]
distutils.dir_util.mkpath (at least as of python 2.7.14) has a cache of created directories. It will not recreate a directory that it has already created, even if that directory was since deleted. This means that a put/delete/put sequence with the same data on a HashFS object will fail on the second put, as the directories will not be recreated after being deleted (by remove_empty) in the delete step.

**Comment by dgilland** [comment]
Closed via 1f3d5ba714fb88f6f372a1ab2ba49ee97b952423
